[versions]
agp = "8.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.1"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
intuit = "1.1.1"
camera = "1.3.2"
mlkit = "17.2.0"
zxing = "3.5.3"
barcode-scanning = "17.2.0"
room-version = "2.8.4"


[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

# Intuit Size
intuit_dp = { group = "com.intuit.sdp", name = "sdp-android", version.ref = "intuit" }
intuit_sp = { group = "com.intuit.ssp", name = "ssp-android", version.ref = "intuit" }

# CameraX
#camera_core = { group = "androidx.camera", name = "camera-core", version.ref = "camera" }
camera_camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "camera" }
camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "camera" }
camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "camera" }

# ML Kit for Barcode Scanning
mlkit = { group = "com.google.mlkit", name = "barcode-scanning", version.ref = "mlkit" }

# zxing for create QR code
zxing = { group = "com.google.zxing", name = "core", version.ref = "zxing" }

# ML kit QR Scanner
barcode-scanning = { group = "com.google.mlkit", name = "barcode-scanning", version.ref = "barcode-scanning" }

# Room Database
roomDB = { group = "androidx.room", name = "room-runtime", version.ref = "room-version" }
roomCP = { group = "androidx.room", name = "room-compiler", version.ref = "room-version" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

